### PR TITLE
pip support

### PR DESCRIPTION
**Pull request by feliciatrinh**

### CODE REVIEW

**Comment by BlackLight** [comment]
+1 on merging this PR.

I'm integrating PicoVoice as an STT engine in my project (it's far faster and more accurate than other models I've tried, even compared to Mozilla Deepspeech). But managing the dependency is tricky without a pip package or even a `setup.py`. Cloning the repo and inserting the path to `binding/python` in `sys.path` isn't exactly straightforward :)

**Comment by gayathry2612** [comment]
I tried to install with pip first for pyaudio and it failed to build the dependencies. Tried conda and it worked.

**Comment by BlackLight** [comment]
@gayathry2612 which issues did you encounter? I've made [my fork](https://github.com/BlackLight/cheetah) that includes @feliciatrinh's PR and fixes the conflicts and I've managed to install it flawlessly via setup.py.

**Comment by Thierryonre** [comment]
I suggest using anaconda to install pyaudio as it does it flawlessly.

**Pull request closed without merging**
